<?php
$modversion['name'] = _MI_XPWEATHER_NAME;
$modversion['version'] = "1.72";
$modversion['description'] = _MI_XPWEATHER_DESC;
$modversion['credits'] = "Original PHPNuke code by - James Nerlinger (jnj@infobin.com)<br>Original Adapte pour XOOPS rc3 par:<br>Philippe<br>http://www.web-liens.net<br><br>French Language Translation<br>Olivier Blazy<br>olivier.blazy@wanadoo.fr<br><br>Spanish Language Translation<br>Bazus<br>http://www.portalactivo.com/espanol.html<br><br>German Language Translation<br>Nobse<br>http://www.e-xoops.de<br><br>Dutch Language Translation<br>Schipper<br>schipper@scheeps.net<br>http://www.scheeps.net<br><br>Logo Image by<br>Vincent Roman<br>http://www.neutronbull.com/";
$modversion['author'] = "1.0 - 1.7 code by:<br>davidd<br>1.72 xoops 2.0.5.2 port by sylvainb";
$modversion['help'] = "The cache directory and files need to be set for both reading and writting by the account the webserver runs under";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "1";
$modversion['image'] = "wweather.jpg";
$modversion['dirname'] = "xp-weather";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "city";
$modversion['tables'][1] = "country";
$modversion['tables'][2] = "region";
$modversion['tables'][3] = "subdiv";
$modversion['tables'][4] = "userweather";
$modversion['tables'][5] = "wmo_stations";

// Menu
$modversion['hasMain'] = 1;

// block
$modversion['blocks'][1]['file'] = "block-XPWeather.php";
$modversion['blocks'][1]['name'] = "XP-Weather Block";
$modversion['blocks'][1]['description'] = "Block_XP-Weather";
$modversion['blocks'][1]['show_func'] = "disp_block_XPWeather";
$modversion['blocks'][1]['edit_func'] = "edit_block_XPWeather";
//-$options[0]=Users can edit/save weather values ) [1/0]
//-$options[1]=block cache time
//-$options[2]=option change time-stamp (internal use, hidden)
//-$options[3]=Show Region with City in block
//-$options[4]=Show cache hit/miss messages
//-$options[5]=Disable weather data cache (don't do this)
//-$options[6]=module physical directory name
//-$options[7]=show change weather values link in block
$modversion['blocks'][1]['options'] = "1|3600|0|1|0|0|".$modversion['dirname']."|0";
?>
